<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ProjectManager.Domain\ProjectManager.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="DTOs/ProjectTasks/" />
    <Folder Include="Queries/" />
    <Folder Include="Services/" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
